version: 0.0
os: linux
files:
  - source: /target/addressbook.war
    destination: /opt/tomcat9/webapps/
hooks:
  BeforeInstall:
    - location: scripts/serviceStop.sh
      timeout: 120
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 120
  ApplicationStart:
    - location: scripts/serviceStart.sh
      timeout: 120
