version: 0.2

phases:
  install:
    commands:
      - wget https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.tar.gz
      - tar xzvf apache-maven-3.9.9-bin.tar.gz -C /opt/
      - export PATH=/opt/apache-maven-3.3.9/bin:$PATH
  build:
    commands:
       - mvn clean install package
artifacts:
  files:
    - target/addressbook.war
    - scripts/serviceStop.sh
    - scripts/serviceStart.sh
    - appspec.yml
